# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
# Specify all the orbs that are used here, only supported in version 2.1 and up
# For more information, see https://circleci.com/orbs/registry/
orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@0.0.8

jobs:
  build:

    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/

    steps:
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: start marklogic
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker run -d --name marklogic -it -p 7997:7997 -p 8001:8001 -p 8002:8002 -p 8200:8200 -p 8201:8201 -p 8000:8000 -e MARKLOGIC_INIT=true -e MARKLOGIC_ADMIN_USERNAME=$MARKLOGIC_ADMIN_USERNAME -e MARKLOGIC_ADMIN_PASSWORD=$MARKLOGIC_ADMIN_PASSWORD $DOCKER_MARKLOGIC_IMAGE
            sleep 10
            while true; do status=`docker exec marklogic curl -sS --retry 10 http://localhost:7997 | grep Healthy`; if [[ "$status" = "Healthy" ]]; then echo "MarkLogic ready"; break; else echo "waiting..."; sleep 1; fi; done
      
      - run:
          name: check marklogic
          command: |
            curl -sS --retry 10 http://localhost:7997

workflows:
  build-and-deploy:
    jobs:
      - build
